version: "3.7"

services:
  clickhouse_server:
    image: yandex/clickhouse-server:${CLICKHOUSE_VERSION:-latest}
    container_name: clickhouse_server
    ports:
      - "${MAPHOST:-}8123:8123"
      - "${MAPHOST:-}9000:9000"
    volumes:
      - ./data:/load_data
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse

volumes:
  clickhouse_data: {}

networks:
  clickhouse:
    driver: bridge
