version: '3.7'

services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./alert.yml:/etc/prometheus/alert.yml
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - node_exporter
    networks:
      - promnet

  node_exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION:-latest}
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
    networks:
      - promnet

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - promnet

volumes:
  prometheus-data: {}
  grafana_data: {}

networks:
  promnet:
    driver: bridge
