global:
  scrape_interval: 5s
  scrape_timeout: 1s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']

remote_write:
  - url: "http://agent:9201/write"
